apiVersion: hell-kitchen/v1
kind: Receipt
metadata:
  name: {{ include "receita.fullname" . }}
  labels:
    {{- include "receita.labels" . | nindent 4 }}
spec:
  name: {{ .Values.receipt.name }}
  ingredients: 
  {{- range $i := .Values.receipt.ingredients }}
    - name: {{$i.name}}
      optional: {{$i.optional}}
      quantity: {{$i.quantity}}
  {{- end}}
  proceedings:
    {{- range $p := .Values.receipt.proceedings }}
    - name: {{$p.name}}
      description: {{$p.description}}
      duration: {{$p.duration}}
      timeUnit: {{$p.timeUnit}}
    {{- end}}

